sonar.projectKey=tasklist-backend
sonar.projectName=TaskList Backend
sonar.projectVersion=1.0.0

# Sources et tests
sonar.sources=src
sonar.tests=src,test
sonar.test.inclusions=**/*.test.ts,**/*.e2e.ts
sonar.sourceEncoding=UTF-8

# Couverture : on fusionne les rapports lcov des tests unitaires ET e2e
sonar.javascript.lcov.reportPaths=coverage/lcov.info,coverage-e2e/lcov.info

# Exclusions
sonar.exclusions=dist/**,node_modules/**,prisma/generated/**,coverage/**,coverage-e2e/**,reports/**
sonar.coverage.exclusions=src/server.ts,**/*.test.ts,**/*.e2e.ts,test/**
